from typing import Any

CONTENT_TYPE_LATEST: str

class CollectorRegistry:
    ...

class Counter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def labels(self, *args: Any, **kwargs: Any) -> Counter: ...
    def inc(self, amount: float = ...) -> None: ...

class Histogram:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def labels(self, *args: Any, **kwargs: Any) -> Histogram: ...
    def observe(self, value: float) -> None: ...

def generate_latest(registry: CollectorRegistry) -> bytes: ...
