# CI pipeline covering linting, type checking, testing, frontend checks,
# Docker image builds, and Playwright end-to-end coverage. Each job mirrors the
# specification outlined in the project backlog so regressions are caught early.
name: CI

on:
  # Validate all pull requests regardless of the source branch.
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"

jobs:
  lint:
    name: Lint (ruff / formatting)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-3.12-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ruff lint
        run: ruff check .
      - name: Check formatting
        run: |
          black --check src tests
          isort --check-only src tests

  typecheck:
    name: Typecheck (mypy)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-3.12-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run mypy
        run: mypy src

  tests:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: typecheck
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-
            pip-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          mkdir -p reports
          pytest --junitxml=reports/pytest-junit.xml --cov=src --cov-report=xml
      - name: Upload coverage and junit
        uses: actions/upload-artifact@v4
        with:
          name: pytest-${{ matrix.python-version }}
          path: |
            coverage.xml
            reports/pytest-junit.xml
      - name: Verify MCP registration
        if: matrix.python-version == '3.12'
        run: |
          python - <<'PY'
          """Ensure all documented MCP tools are registered."""
          import importlib

          module = importlib.import_module("chart_mcp.mcp_main")

          class DummyServer:
              def __init__(self) -> None:
                  self.names: list[str] = []

              def tool(self, name: str):
                  def decorator(func):
                      self.names.append(name)
                      return func

                  return decorator

          server = DummyServer()
          module.register(server)
          expected = set(module.REGISTERED_TOOL_NAMES)
          missing = sorted(expected - set(server.names))
          if missing:
              raise SystemExit(f"Missing MCP tools: {', '.join(missing)}")
          PY

  build-backend:
    name: Build backend image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: tests
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
      - name: Prepare image metadata
        id: image-meta
        run: |
          echo "local-tag=chart-mcp:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          if [ -n "${REGISTRY_URL}" ] && [ -n "${REGISTRY_IMAGE_NAME}" ] && [ -n "${REGISTRY_USERNAME}" ] && [ -n "${REGISTRY_PASSWORD}" ]; then
            echo "should-push=true" >> "$GITHUB_OUTPUT"
            echo "registry-tag=${REGISTRY_URL}/${REGISTRY_IMAGE_NAME}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          else
            echo "should-push=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Log in to registry
        if: ${{ steps.image-meta.outputs.should-push == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: false
          load: true
          tags: ${{ steps.image-meta.outputs.local-tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move Docker cache
        run: |
          if [ -d /tmp/.buildx-cache-new ]; then
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          fi
      - name: Push image to registry
        if: ${{ steps.image-meta.outputs.should-push == 'true' }}
        env:
          LOCAL_TAG: ${{ steps.image-meta.outputs.local-tag }}
          REGISTRY_TAG: ${{ steps.image-meta.outputs.registry-tag }}
        run: |
          docker tag "$LOCAL_TAG" "$REGISTRY_TAG"
          docker push "$REGISTRY_TAG"
      - name: Run container healthcheck
        env:
          API_TOKEN: testingtoken
          ALLOWED_ORIGINS: http://localhost:3000
        run: |
          docker run -d --rm -p 8000:8000 \
            -e API_TOKEN="$API_TOKEN" \
            -e ALLOWED_ORIGINS="$ALLOWED_ORIGINS" \
            -e PLAYWRIGHT=1 \
            --name chart-mcp-ci \
            ${{ steps.image-meta.outputs.local-tag }}
          trap 'docker stop chart-mcp-ci' EXIT
          python docker/healthcheck.py

  build-frontend:
    name: Frontend build & unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck frontend
        run: pnpm --filter ai-chatbot exec tsc --noEmit
      - name: Run Vitest
        run: |
          mkdir -p reports
          pnpm --filter ai-chatbot exec vitest run --coverage --reporter=junit --outputFile=reports/vitest-junit.xml
      - name: Upload Vitest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vitest-results
          path: |
            coverage
            reports/vitest-junit.xml

  playwright-e2e:
    name: Playwright e2e
    runs-on: ubuntu-latest
    timeout-minutes: 40
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm --filter ai-chatbot exec playwright install --with-deps
      - name: Start Next.js server
        env:
          PORT: 3000
          PLAYWRIGHT: "1"
          CI_PLAYWRIGHT: "1"
          AUTH_SECRET: ${{ env.AUTH_SECRET || 'playwright-secret' }}
          MCP_API_BASE: ${{ env.MCP_API_BASE || 'http://127.0.0.1:3000/api/test-backend' }}
          MCP_SESSION_USER: ${{ env.MCP_SESSION_USER || 'playwright-e2e' }}
          MCP_API_TOKEN: ${{ env.MCP_API_TOKEN || 'test-token' }}
          NEXT_PUBLIC_API_BASE_URL: ${{ env.NEXT_PUBLIC_API_BASE_URL || 'http://127.0.0.1:3000/api/test-backend' }}
          NEXT_PUBLIC_ENABLE_E2E_STREAM_DEBUG: ${{ env.NEXT_PUBLIC_ENABLE_E2E_STREAM_DEBUG || '1' }}
        run: |
          cd frontend/ai-chatbot
          LOG_FILE="$GITHUB_WORKSPACE/frontend/ai-chatbot/.next-dev.log"
          pnpm run dev:playwright > "$LOG_FILE" 2>&1 &
          NEXT_PID=$!
          echo "NEXT_PID=$NEXT_PID" >> "$GITHUB_ENV"
          echo "NEXT_LOG=$LOG_FILE" >> "$GITHUB_ENV"
      - name: Wait for frontend availability
        run: |
          # Poll the local harness until Next.js responds or we hit the guardrail.
          ATTEMPTS=120
          SLEEP_SECONDS=3
          for attempt in $(seq 1 "$ATTEMPTS"); do
            if curl -sf http://127.0.0.1:3000 >/dev/null; then
              echo "Frontend became ready after $attempt attempt(s)."
              exit 0
            fi
            if [ -n "${NEXT_LOG:-}" ] && [ -f "$NEXT_LOG" ] && grep -q "Failed to start server" "$NEXT_LOG"; then
              echo "Next.js reported a startup failure—dumping log:" >&2
              cat "$NEXT_LOG" >&2
              exit 1
            fi
            sleep "$SLEEP_SECONDS"
          done
          echo "Frontend did not become ready within $((ATTEMPTS * SLEEP_SECONDS)) seconds." >&2
          if [ -n "${NEXT_LOG:-}" ] && [ -f "$NEXT_LOG" ]; then
            echo "--- Next.js server log ---" >&2
            cat "$NEXT_LOG" >&2
          fi
          exit 1
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:3000
          PLAYWRIGHT_SKIP_WEB_SERVER: "1"
        run: pnpm --filter ai-chatbot exec playwright test --reporter=line
      - name: Stop Next.js server
        if: always()
        run: |
          if [ -n "${NEXT_PID:-}" ]; then
            kill "$NEXT_PID" || true
          fi
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
